version: "3.7"

services:

  flask_api:
    build: ./api
    container_name: youtube_sampler_api
    restart: always
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./api/app.py
      PYTHONUNBUFFERED: 1
      PYTHONIOENCODING: UTF-8
    volumes:
      - ./api/app:/app
    ports:
      - "420:420"
    depends_on:
      - redis

  worker:
    build:
      context: ./api
    command: celery --app=app.celery worker --loglevel=DEBUG
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./api/app:/app
    depends_on:
      - flask_api
      - redis


  redis:
    image: "redis:alpine"
