version: "3.7"

services:

  redis:
    image: "redis:alpine"

  flask_api:
    build: .
    container_name: youtube_sampler_api
    restart: "no"
    environment:
      FLASK_DEBUG: 1
      PYTHONUNBUFFERED: 1
      PYTHONIOENCODING: UTF-8
    volumes:
      - .:/home/youtube_sampler
    ports:
      - "420:420"
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A run.celery_app worker --loglevel=INFO -f app/logs/celery.log
    volumes:
      - .:/home/youtube_sampler
    depends_on:
      - redis
